[package]
name = "raptor"
description = "Parallelized, coverage-guided, mutational Solidity smart contract fuzzing, powered by LibAFL and revm."
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/pyk/raptor"

[lib]
name = "raptor"
path = "src/lib.rs"

[dependencies]
# Error handling
anyhow = "1.0.100"

# CLI
clap = { version="4.5.54", features = ["derive"] }
clap-verbosity-flag = { version="3.0.4", features = ["tracing"] }

# Logging & Tracing
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# JSON & TOML
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
toml = "1.1.2"

# Fuzzer
libafl = "0.15.3"
libafl_bolts = "0.15.3"

# EVM
revm = "38.0.0"

# Hex decoding for foundry artifacts
hex = "0.4.3"

# ABI & Foundry integration
alloy-json-abi = "1.6.0"
alloy-dyn-abi = "1.6.0"
alloy-primitives = "1.6.0"

# Corpus file naming
uuid = { version = "1", features = ["v4"] }
