.PHONY: TargetContractBasicOnce
TargetContractBasicOnce:
	@genhtml reports/TargetContractBasicOnce.info -o coverage/TargetContractBasicOnce --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractBasicOnce/

.PHONY: TargetContractBasicTwice
TargetContractBasicTwice:
	@genhtml reports/TargetContractBasicTwice.info -o coverage/TargetContractBasicTwice --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractBasicTwice/

.PHONY: TargetContractWithLoop
TargetContractWithLoop:
	@genhtml reports/TargetContractWithLoop.info -o coverage/TargetContractWithLoop --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractWithLoop/

.PHONY: TargetContractWithLib
TargetContractWithLib:
	@genhtml reports/TargetContractWithLib.info -o coverage/TargetContractWithLib --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractWithLib/

.PHONY: TargetContractWithLibLinked
TargetContractWithLibLinked:
	@genhtml reports/TargetContractWithLibLinked.info -o coverage/TargetContractWithLibLinked --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractWithLibLinked/

.PHONY: TargetContractWithInterface
TargetContractWithInterface:
	@genhtml reports/TargetContractWithInterface.info -o coverage/TargetContractWithInterface --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractWithInterface/

.PHONY: TargetContractWithIf
TargetContractWithIf:
	@genhtml reports/TargetContractWithIf.info -o coverage/TargetContractWithIf --flat
	@python3 -m http.server 8002 --bind 0.0.0.0 --directory coverage/TargetContractWithIf/
