//! Foundry build-info types and parsing.
//!
//! Build-info files are generated by the Solidity compiler during compilation
//! and stored in `out/build-info/*.json`. They contain metadata about the
//! compilation, including the `source_id_to_path` map that is required for
//! coverage reporting.
//!
//! The `source_id_to_path` map is the only source of the mapping from numeric
//! source indices (used in the deployed bytecode source map) to project-relative
//! source file paths.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::Deserialize;

use crate::foundry::artifact::ArtifactId;

/// A single build-info file loaded from a Foundry project.
///
/// Build-info is generated by the compiler and contains the
/// `source_id_to_path` mapping required to resolve source indices from the
/// bytecode source map back to actual source file paths.
#[derive(Debug, Clone, Deserialize)]
pub struct BuildInfo {
    /// Map from numeric source index to project-relative source path.
    #[serde(rename = "source_id_to_path")]
    source_id_to_path: HashMap<String, PathBuf>,
}

impl BuildInfo {
    /// Load a build-info file from a JSON file on disk.
    pub fn from_json(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read build-info: {}", path.display()))?;
        let info: BuildInfo = serde_json::from_str(&content)
            .with_context(|| format!("failed to parse build-info: {}", path.display()))?;
        Ok(info)
    }

    /// Load the source index map for a specific artifact from a project's
    /// `out/build-info` directory.
    ///
    /// Foundry incremental builds create multiple build-info files, one per
    /// compilation unit. Source IDs are only unique within a compilation unit,
    /// so merging all build-info files globally can produce conflicts or stale
    /// mappings for artifacts that were not rebuilt.
    ///
    /// This method finds the most recent build-info file whose
    /// `source_id_to_path` maps the artifact's numeric source ID to the
    /// artifact's source file path. This strong match ensures the build-info
    /// is the one that produced the artifact (or a later recompilation of the
    /// same unit), so its source IDs are consistent with the artifact's bytecode
    /// source map.
    pub fn load_source_index_for_artifact(
        project_path: impl AsRef<Path>,
        artifact_id: &ArtifactId,
        artifact_source_id: usize,
    ) -> Result<HashMap<usize, PathBuf>> {
        let build_info_dir = project_path.as_ref().join("out").join("build-info");

        if !build_info_dir.exists() {
            return Ok(HashMap::new());
        }

        let mut files = Vec::new();
        for entry in fs::read_dir(&build_info_dir).with_context(|| {
            format!(
                "failed to read build-info dir: {}",
                build_info_dir.display()
            )
        })? {
            let entry = entry?;
            let path = entry.path();
            if path.extension() != Some("json".as_ref()) {
                continue;
            }
            let modified = fs::metadata(&path)
                .and_then(|m| m.modified())
                .unwrap_or(std::time::SystemTime::UNIX_EPOCH);
            files.push((path, modified));
        }

        // Most recent first -- the first build-info that maps the artifact's
        // numeric source ID to its source file path is the correct one.
        files.sort_by(|a, b| b.1.cmp(&a.1));

        for (path, _) in files {
            let info = BuildInfo::from_json(&path)?;
            let key = artifact_source_id.to_string();
            if matches!(info.source_id_to_path.get(&key), Some(p) if p == &artifact_id.path) {
                let mut map = HashMap::new();
                for (k, v) in info.source_id_to_path {
                    let Ok(idx) = k.parse::<usize>() else {
                        continue;
                    };
                    map.insert(idx, v);
                }
                return Ok(map);
            }
        }

        bail!(
            "no build-info file found for source path `{}` with source ID {}. \
             Run `forge clean && forge build --ast --extra-output storageLayout` before loading coverage.",
            artifact_id.path.display(),
            artifact_source_id
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_build_info() {
        let json = r#"{
            "id": "test-build-id",
            "language": "Solidity",
            "source_id_to_path": {
                "0": "src/Counter.sol",
                "1": "src/Helper.sol"
            }
        }"#;
        let info: BuildInfo = serde_json::from_str(json).unwrap();
        assert_eq!(
            info.source_id_to_path.get("0"),
            Some(&PathBuf::from("src/Counter.sol"))
        );
        assert_eq!(
            info.source_id_to_path.get("1"),
            Some(&PathBuf::from("src/Helper.sol"))
        );
    }
}
