//! Foundry build-info types and parsing.
//!
//! Build-info files are generated by the Solidity compiler during compilation
//! and stored in `out/build-info/*.json`. They contain metadata about the
//! compilation, including the `source_id_to_path` map that is required for
//! coverage reporting.
//!
//! The `source_id_to_path` map is the only source of the mapping from numeric
//! source indices (used in the deployed bytecode source map) to project-relative
//! source file paths.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Deserialize;

/// A single build-info file loaded from a Foundry project.
///
/// Build-info is generated by the compiler and contains the
/// `source_id_to_path` mapping required to resolve source indices from the
/// bytecode source map back to actual source file paths.
#[derive(Debug, Clone, Deserialize)]
pub struct BuildInfo {
    /// Map from numeric source index to project-relative source path.
    #[serde(rename = "source_id_to_path")]
    source_id_to_path: HashMap<String, PathBuf>,
}

impl BuildInfo {
    /// Load a build-info file from a JSON file on disk.
    pub fn from_json(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read build-info: {}", path.display()))?;
        let info: BuildInfo = serde_json::from_str(&content)
            .with_context(|| format!("failed to parse build-info: {}", path.display()))?;
        Ok(info)
    }

    /// Load all build-info files from a project's `out/build-info` directory.
    ///
    /// Returns a map of `source_index -> path` merged from all build-info files
    /// found in the directory. If the directory does not exist, returns an
    /// empty map.
    pub fn load_source_index_map(
        project_path: impl AsRef<Path>,
    ) -> Result<HashMap<usize, PathBuf>> {
        let build_info_dir = project_path.as_ref().join("out").join("build-info");
        let mut map = HashMap::new();

        if !build_info_dir.exists() {
            return Ok(map);
        }

        for entry in fs::read_dir(&build_info_dir).with_context(|| {
            format!(
                "failed to read build-info dir: {}",
                build_info_dir.display()
            )
        })? {
            let entry = entry?;
            let path = entry.path();
            if path.extension() != Some("json".as_ref()) {
                continue;
            }
            let info = BuildInfo::from_json(&path)?;
            for (k, v) in info.source_id_to_path {
                if let Ok(idx) = k.parse::<usize>() {
                    map.insert(idx, v);
                }
            }
        }

        Ok(map)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_build_info() {
        let json = r#"{
            "id": "test-build-id",
            "language": "Solidity",
            "source_id_to_path": {
                "0": "src/Counter.sol",
                "1": "src/Helper.sol"
            }
        }"#;
        let info: BuildInfo = serde_json::from_str(json).unwrap();
        assert_eq!(
            info.source_id_to_path.get("0"),
            Some(&PathBuf::from("src/Counter.sol"))
        );
        assert_eq!(
            info.source_id_to_path.get("1"),
            Some(&PathBuf::from("src/Helper.sol"))
        );
    }
}
